defaults: &defaults
  url: "amqp://localhost:5672"
  queue_name: "psd.s2.samples"
  durable: true
  empty_queue_disconnect_interval: 0
  message_timeout: 120

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
